#!/bin/bash
# Overall package builder script. This is the one to run when you're
# doing a build

# Should be ensuring we have the following tools installed: 
# libtoolize autoconf m4 fromdos xmlto flex bison

set -e

trap

PACKAGE=$1
PACKAGE_BUILDER_BASE=.
. ./config
. ./helpers/helper_functions.sh
TMPDIR=/tmp/$PACKAGE.$$

cleanup() {
    echo "Erasing temporary directory: $TMPDIR"
    rm -rf "$TMPDIR"
}

trap cleanup 1 2 3 6


if [ ! -f "scripts/$PACKAGE" ] ; then
    echo "Package '$PACKAGE' not found" 2>&1
    exit 1
fi

executable_required "flex" "bison" "fromdos" "git" "svn" "autoconf" "libtool" "shtool" "xmlto" "pmake"

# Ensure all of the directories are in place
if [ ! -d "${PACKAGE_DIR}" ] ; then
    mkdir ${PACKAGE_DIR}
fi

if [ ! -d "${BUILD_DIR}" ] ; then
    mkdir ${BUILD_DIR}
fi

if [ ! -d "${STAGING}" ] ; then
    mkdir ${STAGING}
fi

# Make a temporary build directory, and do the build in there
mkdir $TMPDIR
pushd build
export NAME=$PACKAGE
. ../scripts/$PACKAGE $TMPDIR
popd

cleanup

