#!/bin/bash

ROOT=$(realpath $(dirname $0))

set -e
. ${ROOT}/config

PACKAGES_LIST=$1
DEST=$2
DEVICE_TABLE=${3:-${ROOT}/device_table}

BINARY_BASE=${TOOLCHAIN_DIR}/arm-none-linux-gnueabi/libc/armv4t

if [ -z "$PACKAGES_LIST" -o -z "$DEST" -o ! -f "$PACKAGES_LIST" ] ; then
    echo "Usage: $0 packages_list_file output_directory [device_table]"
    exit 1
fi

if [ -e "$DEST" ] ; then
    echo "Output directory $DEST already exists"
    exit 1
fi

## Helper functions
copy_lib () {
    base=$1
    shift
    for f in $* ; do
        echo -n "."
        cp -a "$BINARY_BASE"/$base/$f "$DEST"/$base &
    done
}

install_package() {
    package=$1
    FILE=`realpath ${PACKAGE_DIR}/${package}_*.ipk`
    #echo $FILE
    if [ ! -f ${FILE} ] ; then
        echo "Cannot find package '${package}'" >&2
        exit 1
    fi
    ar p ${FILE} data.tar.gz | tar -xmzC ${DEST} --no-overwrite-dir --delay-directory-restore &
    echo -n "."
}

make_device () {
    device="$DEST"/$1
    type=$2
    mode=$3
    uid=$4
    gid=$5
    major=$6
    minor=$7
    start=$8
    inc=$9
    count=${10}

    dir=`dirname $device`

    if [ -n "$dir" -a ! -d "$dir" ] ; then
        mkdir -p "$dir"
    fi

    if [ "$type" == "d" ] ; then
        mkdir "$device"
    elif [ "$type" == "c" -o "$type" == "b" ] ; then
        if [ "$count" == "-" -o -z "$count" ] ; then
            sudo mknod "$device" $type $major $minor
        else
            i=$start
            pos=$(( $minor ))
            while [ "$i" -le "$count" ] ; do
                # Background them to speed it up
                sudo mknod "$device$i" $type $major $pos
                pos=$(( $pos + $inc ))
                i=$(( $i + 1 ))
        done
        fi
    elif [ "$type" == "l" ] ; then
        ln -s "$mode" "$device"
    fi
    echo -n "."
}

make_devices () {
    FILE=$1
    cat $1 | while read line ; do
        if [ "${line:0:1}" != "#" ] ; then
            make_device $line
        fi
    done
}


# Build directory structure
mkdir -p "$DEST/lib" "$DEST/dev" "$DEST/proc" "$DEST/sys" "$DEST/etc/init.d" "$DEST/var/tmp" "$DEST/home" "$DEST/mnt" "$DEST/var/run" "$DEST/usr/local/bin" "$DEST/usr/lib"

# Copy libraries (ARM only)
if [ "${ARCH}" == "arm" ] ; then
    echo -n "  Copying Libraries "
    ln -s /var/tmp "$DEST/tmp"

    # Copy toolchain libraries
    copy_lib lib ld-*.so libc-*.so libm-*.so libcrypt-*.so libnss_files-*.so libnss_dns-*.so libresolv-*.so libgcc_s.so.* libpthread-*.so librt-*.so libdl-*.so libnsl-*.so libutil-*.so libthread_db-*.so
    copy_lib usr/lib libstdc++.so*
    echo
fi

# Copy default root files
cp -a ${ROOT}/root_files/* "${DEST}/"
find "${DEST}" -depth -name ".svn" -exec rm -rf {} \;

# Install packages
echo -n "  Installing Packages "
cat $PACKAGES_LIST | while read p ; do
    if [ -z "$p" ] ; then
        continue
    fi
    install_package $p
done
echo

# Build device files
echo -n "  Building Device Files..."
make_devices ${DEVICE_TABLE}
echo

# Wait for any background stuff to finish
wait

if [ "$STRIP_ROOTFS" == "1" ] ; then
    echo -n "  Stripping binaries..."
    FILES="${DEST}/lib/* ${DEST}/bin/* ${DEST}/usr/lib/* ${DEST}/usr/bin/*"
    for f in $FILES ; do
        if [ -f $f ] ; then
            ${TOOLCHAIN_DIR}/bin/arm-none-linux-gnueabi-strip $f >/dev/null 2>&1 || true
            echo -n "."
        fi
    done
    echo
fi

# Finalise
/sbin/ldconfig -r "$DEST"

