#!/bin/bash
BASEDIR=$(dirname $(readlink -f $0))
PKG_CONFIG_LIBDIR=${PKG_CONFIG_LIBDIR:-$BASEDIR/staging/lib/pkgconfig}
export PKG_CONFIG_LIBDIR
if [ "$1" == "--atleast-pkgconfig-version" ] ; then
    /usr/bin/pkg-config $@
else
    /usr/bin/pkg-config --define-variable=prefix=$BASEDIR/staging $@
fi

