#!/bin/bash
BASEDIR=$(dirname $(readlink -f $0))
export PKG_CONFIG_LIBDIR=$BASEDIR/staging/lib/pkgconfig
if [ "$1" == "--atleast-pkgconfig-version" ] ; then
    /usr/bin/pkg-config $@
else
    /usr/bin/pkg-config --define-variable=prefix=$BASEDIR/staging $@
fi

