#!/bin/bash
# Overall package builder script. This is the one to run when you're
# doing a build

set -e

PACKAGE=$1
. ./config
. ./helper_functions.sh

if [ ! -f "scripts/$PACKAGE" ] ; then
    echo "Package not found" 2>&1
    exit 1
fi

if [ ! -d "${PACKAGE_DIR}" ] ; then
    mkdir ${PACKAGE_DIR}
fi

if [ ! -d "${BUILD_DIR}" ] ; then
    mkdir ${BUILD_DIR}
fi

TMPDIR=/tmp/$PACKAGE.$$
mkdir $TMPDIR
pushd build
. ../scripts/$PACKAGE $TMPDIR
popd

rm -rf $TMPDIR

