#!/bin/bash

set -e

PACKAGE_NAME=$1

# Create the build directory if it does not exist
if [ ! -d "build" ]; then
    mkdir build
fi	

if [ -z "$PACKAGE_NAME" ] ; then
    PACKAGE_NAME=full_packages_list
fi

cat full_packages_list | while read package ; do
    ./update_package $package
done
