#!/bin/bash

set -e

PACKAGE_NAME=$1

if [ -z "$PACKAGE_NAME" ] ; then
    PACKAGE_NAME=full_packages_list
fi

for package in `cat $PACKAGE_NAME` ; do
    if [ "${SKIP_EXISTING}" == 1 -a -f packages/${package}_*.ipk ] ; then
        echo "Skipping $package - its already built"
    else
        echo "Building $package..."
        ./update_package $package
    fi
done
