version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install build requirements
          command: |
            set -x
            apt-get update
            apt-get install -y make gcc wget bzip2 git
            mkdir -p /tools/arm-2013.05
            wget -nv https://sourcery.mentor.com/GNUToolchain/package11447/public/arm-none-linux-gnueabi/arm-2013.05-24-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2 -O - | tar -C /tools/arm-2013.05 -xj
      - checkout
      - run:
          name: Build
          command: ./pbuild build-all minimal_packages_list
