#!/bin/sh
echo "Mounting system filesystems..."
mount -a
echo "Starting local networking..."
ifconfig lo up
hostname snapper
telnetd

echo "Setting hotplug script..."
echo /sbin/hotplug > /proc/sys/kernel/hotplug

CONSOLE=`sed 's/.*console=\([^, ]*\).*/\1/' /proc/cmdline`
if [ -z "$CONSOLE" ] ; then
        CONSOLE=ttyS0
fi
echo "Setting up console $CONSOLE..."
ln -sf $CONSOLE /dev/tty_console

