#!/bin/sh

NAME=bluez
VERSION=4.69
SOURCE=http://www.kernel.org/pub/linux/bluetooth/bluez-${VERSION}.tar.gz
export DBUS_LIBS="-L${STAGING}/lib -ldbus-1"
CONFIGURE_PARAMS="--disable-silent-rules"

do_generic "$1"

