#!/bin/bash

set_config() {
    config=$1
    option=$2
    value=$3
    if [ -z "$value" ] ; then
        value="y"
    fi
    sed -i "s/^# $option .*$/$option=$value/" $config
}

clear_config() {
    config=$1
    option=$2
    sed -i "s/^$option=.*$/# $option is not set/" $config
}

VERSION=1.13.3
SOURCE=http://busybox.net/downloads/busybox-${VERSION}.tar.bz2

download_unpack "$SOURCE"
make CROSS_COMPILE=${CROSS} ARCH=${ARCH} CFLAGS=${CFLAGS} defconfig
# Turn on some options that we like
set_config .config CONFIG_FEATURE_EDITING_FANCY_PROMPT
set_config .config CONFIG_ASH_EXPAND_PRMT
# Saved history is annoying across multiple terminals
clear_config .config CONFIG_FEATURE_EDITING_SAVEHISTORY

make CROSS_COMPILE=${CROSS} ARCH=${ARCH} CFLAGS=${CFLAGS} oldconfig
make CROSS_COMPILE=${CROSS} ARCH=${ARCH} CFLAGS=${CFLAGS} -j4
make CROSS_COMPILE=${CROSS} ARCH=${ARCH} CFLAGS=${CFLAGS} busybox.links
./applets/install.sh "$1" --symlinks

build_package busybox ${VERSION} $1

