#!/bin/sh

NAME=dbus
VERSION=1.2.24
SOURCE=http://dbus.freedesktop.org/releases/dbus/dbus-${VERSION}.tar.gz
CONFIGURE_PARAMS="--without-x"

post_install() {
    mkdir -p "$1"/etc/dbus-1/session.d
    mkdir -p "$1"/var/lib/dbus
    sed -i "s#libdir='//lib'#libdir='${STAGING}/lib'#" "$1"/lib/libdbus-1.la
}

do_generic "$1"

