#!/bin/bash

if [ -z "$FILENAME" ] ; then
    FILENAME=`basename $SOURCE`
fi

if [ ${FILENAME%.tar.gz} != ${FILENAME} ] ; then
    EXTRACT="tar xfz"
    DIRNAME=${FILENAME%.tar.gz}
elif [ ${FILENAME%.tar.bz2} != ${FILENAME} ] ; then
    EXTRACT="tar xfj"
    DIRNAME=${FILENAME%.tar.bz2}
elif [ ${FILENAME%.zip} != ${FILENAME} ] ; then
    EXTRACT="unzip"
    DIRNAME=${FILENAME%.zip}
else
    echo "Unknown extraction name: $FILENAME"
    exit 1
fi

if [ -n "${FORCE_DIRNAME}" ] ; then
    DIRNAME=${FORCE_DIRNAME}
fi

if [ ! -f $FILENAME ] ; then
    wget $SOURCE -O ${FILENAME}
fi
if [ ! -d ${DIRNAME} ] ; then
    ${EXTRACT} ${FILENAME}
fi
pushd ${DIRNAME}
if [ ! -f configure ] ; then
    LDFLAGS=$LDFLAGS CFLAGS=$CFLAGS ./autogen.sh --host=$HOST $CONFIGURE_PARAMS
fi

LDFLAGS=$LDFLAGS CFLAGS=$CFLAGS ./configure --host=$HOST $CONFIGURE_PARAMS
make -j4
make install prefix=$1
popd

if [ "$BUILD_LIBRARY" == "1" ] ; then
    build_lib_package ${NAME} ${VERSION} "$1"
else
    build_package ${NAME} ${VERSION} "$1"
fi
