#!/bin/sh

NAME=libpng
VERSION=1.4.7
SOURCE=ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-${VERSION}.tar.bz2

post_unpack() {
    sed -i 's/^.*-Wl,--version-script=libpng.vers.*$//g' Makefile.am
    sed -i 's/^.*-Wl,--version-script=libpng.vers.*$//g' Makefile.in
}

do_generic "$1"
