#!/bin/sh

NAME=libtar
VERSION=1.2.11
#SOURCE=ftp://ftp.feep.net/pub/software/libtar/libtar-1.2.11.tar.gz
SOURCE=http://ftp.debian.org/debian/pool/main/libt/libtar/libtar_1.2.11.orig.tar.gz

CONFIGURE_PARAMS="--prefix=$1"

# Libtar's configure script is broken for cross-compiling :-(
export compat_cv_func_makedev_three_args=no
export compat_cv_func_snprintf_works=yes
export AR=${CROSS}ar

download_unpack "$SOURCE" "" libtar-1.2.11
do_configure
do_configure
make

# Manual install
if [ ! -d "%1"/lib ]; then
	mkdir -p "$1"/lib
fi
if [ ! -d "%1"/include ]; then
	mkdir -p "$1"/include
fi	
cp lib/libtar.a "$1"/lib
cp lib/libtar.h "$1"/include

build_generic_package "$1"

