#!/bin/bash

NAME=mplayer
VERSION=svn
SOURCE=svn://svn.mplayerhq.hu/mplayer/trunk

# Make sure we're up to date
if [ ! -d mplayer ] ; then
    svn co "$SOURCE" mplayer
    cd mplayer
else
    cd mplayer
    svn up
fi

./configure --prefix=/ --enable-cross-compile --enable-armv5te --yasm='' --target=${HOST} --host-cc=gcc --cc=${CROSS}gcc --enable-fbdev --enable-alsa
do_make
do_install "$1"
build_generic_package "$1"
cd ..

