#!/bin/bash

NAME=ncurses
VERSION=5.7
SOURCE=http://ftp.gnu.org/pub/gnu/ncurses/ncurses-${VERSION}.tar.gz

CONFIGURE_PARAMS="--enable-overwrite"

do_build_install "$1"
build_package "${NAME}"-terminfo "${VERSION}" "$1" ".*/terminfo/.*"
build_generic_package "$1"


