#!/bin/bash

NAME=opkg
VERSION=0.1.8
SOURCE=http://opkg.googlecode.com/files/opkg-0.1.8.tar.gz
export CURL_CFLAGS=-I${STAGING}/include
export CURL_LIBS="-L${STAGING}/lib -lcurl"
CONFIGURE_PARAMS="--disable-openssl --disable-ssl-curl --disable-gpg LDFLAGS=-ldl"
pre_install() {
    mkdir -p "$1"/usr/lib/opkg
    touch "$1"/usr/lib/opkg/lock
}

do_generic "$1"

