#!/bin/sh

NAME=sdl-image
VERSION=1.2.10
SOURCE=http://www.libsdl.org/projects/SDL_image/release/SDL_image-${VERSION}.tar.gz
BUILD_LIBRARY=1

export LIBPNG_CFLAGS=-I${STAGING}/include/libpng14
export LIBPNG_LIBS=-lpng14

. $BASE/scripts/generic

