#!/bin/sh

NAME=sdl-ttf
VERSION=2.0.10
SOURCE=http://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-${VERSION}.tar.gz
CONFIGURE_PARAMS="--without-x --disable-gl --with-sdl-exec-prefix=${STAGING} --with-sdl-prefix=${STAGING}"

do_generic "$1"

