#!/bin/sh

NAME=tslib
VERSION=1.0
SOURCE=http://ftp.debian.org/debian/pool/main/t/tslib/tslib_1.0.orig.tar.gz

# To work around some weird rpl_malloc oddity in the configure script
export ac_cv_func_malloc_0_nonnull=yes

download_unpack "$SOURCE" tslib_1.0.orig.tar.gz tslib-1.0
./autogen.sh
do_configure
do_make
do_install "$1"
build_generic_package "$1"

