#!/bin/bash

NAME=wireless-tools
VERSION=29
SOURCE=http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/wireless_tools.${VERSION}.tar.gz

download_unpack ${SOURCE}
make CC=${CROSS}gcc
make CC=${CROSS} PREFIX=$1 install

build_generic_package "$1"
